server:
  port: 8000
  servlet:
    context-path: /redis

#redis配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: 123456
    timeout: 60000
    #最大连接
    max-active: 1000
    #最小空闲连接
    min-idle: 2
    #最大空闲连接
    max-idle: 10
    #连接池最大阻塞等待时间，负数不限制
    max-wait: -1
